name: Python Lab10 Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run Lab10 script
      run: |
        python divisors.py 100
